# Generated by Django 5.2.8 on 2025-12-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian')], db_index=True, default='student', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(blank=True, db_index=True, help_text='Required for students', max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronic Engineering'), ('ICT', 'Information & Communication Technology'), ('Robotics', 'Robotics & Automation'), ('Cyber_Security', 'Cyber Security')], db_index=True, help_text='Required for students', max_length=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'status'], name='accounts_us_role_4a0da6_idx'), models.Index(fields=['department', 'status'], name='accounts_us_departm_109414_idx')],
            },
        ),
    ]
