# Generated by Django 5.2.7 on 2025-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userapproval_rejection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a book cover image (JPG, PNG)', null=True, upload_to='book_covers/'),
        ),
    ]
