# Generated by Django 5.2.8 on 2025-11-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ICT', 'ICT'), ('Robotics', 'Robotics')], max_length=20),
        ),
    ]
